[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"


[project]
name="calcutils_byiringiroaloys"
version="0.1.0"
description="A simple student tutorial math utility package"
readme="README.md"
authors=[
    {name = "Aloys Byiringiro", email = "byiringiroaloys@rca.ac.rw"}
]
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.8"
dependencies = []


[project.urls]
Homepage = "https://github.com/byiringiro-aloys/byiringiroaloys-calcutils"